image: gcc:7.2

build:
  stage: build
  before_script: 
    - apt update && apt -y install cmake libglew-dev libglfw3-dev libglm-dev
  script: 
    - mkdir _build && cd _build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=_install
    - cmake --build . --target install
  artifacts:
    paths:
      - _install

test:
  stage: test
  script:
    - cd _build && ctest .
